In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
list_

['1', '2', '3', '4', '5']

### q1)Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
### to print the data types of both the variables.

answer:
list_ is a Python list containing strings: '1', '2', '3', '4', and '5'.
array_list is a NumPy array created from the list_ variable.

In this code, type(list_) will show that list_ is of type list, type(array_list) will show that array_list is a NumPy array, and array_list.dtype will show the data type of elements within the NumPy array (which will be determined by the data type of the original list elements). In this case, the data type of elements in array_list will be str (string).

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
print("Data type of array_list elements:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>
Data type of array_list elements: <U1


### Q2. Write a code to print the data type of each and every element of both the variables list_ and
### arra_list.

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and
### arra_list? If so then print the data types of each and every element present in both the variables, list_
### and arra_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data types of the elements present in the variables list_ and array_list after changing the dtype of the array_list variable to int. The elements in list_ are originally strings, but when you create the array_list with dtype=int, the elements will be converted to integers.

In [7]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In this code snippet, the array_list is created with dtype=int, which means that the elements in array_list will be integers. The output of the code will show that the elements in the list_ variable are of type <class 'str'>, while the elements in the array_list variable are of type <class 'numpy.int32'>

In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
#shape of array is
print('shape of arrray is',num_array.shape)
#size of the array is
print('size of array is',num_array.size)

shape of arrray is (2, 3)
size of array is 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
import numpy as np

In [21]:
arr_zeros=np.zeros((3,3),dtype=int)

In [22]:
print(arr_zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
arr_zeros.dtype

dtype('int32')

In [24]:
arr_zeros.shape

(3, 3)

In [25]:
arr_zeros.size

9

### using with out functions

In [34]:
a=np.array([0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
a.reshape(3,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [26]:
import numpy as np

In [29]:
arr_identity=np.eye(N=5,M=5,dtype=int)

In [30]:
arr_identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])